import axios from "axios";
import type { NextPage } from "next";
import Head from "next/head";
import { useRouter } from "next/router";
import { Box, Button, Text, Pagination, Divider, Stack } from "@mantine/core";
import { useLogin } from "@soul-project/react-soul-utils";
import { File } from "tabler-icons-react";
import { useQuery } from "react-query";

import NavigationBar from "src/components/NavigationBar";
import Footer from "src/components/Footer";
import Page from "src/components/Page";
import usePagination from "src/hooks/usePagination";

const Author: NextPage = () => {
  const router = useRouter();
  const { userId } = router.query;

  const { data } = useQuery(
    [`/api/authors/posts`, userId],
    async () => {
      const { data } = await axios.get<{ posts: Post[]; totalCount: number }>(
        `/api/authors/${userId}/posts`,
        { params: { page: 1, numItemsPerPage: 10 } }
      );
      return data;
    },
    { enabled: !!userId }
  );

  const { userCredentials, login, logout, isLoggingIn } = useLogin({
    platformId: 2,
    callback: "http://localhost:3000",
  });

  const { page, setPage, totalPages } = usePagination(
    data?.totalCount || 0,
    router
  );

  return (
    <div>
      <Head>
        <title>Liberal</title>
        <meta
          name="description"
          content="Generated by create next app"
          charSet="utf-8"
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Page>
          <NavigationBar
            username={userCredentials?.username}
            onLogin={login}
            onLogout={logout}
            isLoggingIn={isLoggingIn}
            primaryButton={
              <Button component="a" href="/new" rightIcon={<File />}>
                New Article
              </Button>
            }
          />
          <Box
            sx={() => ({
              padding: "10px 30px 30px 30px",
            })}
          >
            <Text
              sx={() => ({
                color: "white",
                fontSize: "30px",
              })}
            >
              {userCredentials?.username}
            </Text>
            <Divider my="sm" />
            {data && (
              <Box>
                <Stack>
                  {data.posts.map((post) => (
                    <Box key={post.cid}>
                      <Text color="white">{post.title}</Text>
                    </Box>
                  ))}
                </Stack>
                <Pagination
                  total={totalPages}
                  page={page}
                  onChange={setPage}
                  sx={() => ({ marginTop: "30px" })}
                />
              </Box>
            )}
          </Box>
        </Page>
      </main>
      <Footer />
    </div>
  );
};

export default Author;

type Post = {
  cid: string;
  title: string;
};
