import axios from "axios";
import { useEffect, useState } from "react";
import type { NextPage } from "next";
import Head from "next/head";
import { useRouter } from "next/router";
import { Box, Button, Text } from "@mantine/core";
import { useLogin } from "@soul-project/react-soul-utils";
import { File } from "tabler-icons-react";

import NavigationBar from "src/components/NavigationBar";
import Footer from "src/components/Footer";
import Page from "src/components/Page";

const Author: NextPage = () => {
  const router = useRouter();
  const { userId } = router.query;

  const { userCredentials, login, logout, isLoggingIn } = useLogin({
    platformId: 2,
    callback: "http://localhost:3000",
  });
  const [username, setUsername] = useState<string | undefined>();

  useEffect(() => {
    const getUsername = async (userId: string) => {
      const {
        data: { username },
      } = await axios.get(`/api/authors/${userId}`);
      setUsername(username);
    };
    if (userId) {
      getUsername(userId as string);
    }
  }, [userId]);
  // TODO: Get posts of this user, create endpoint on nextjs to do that

  return (
    <div>
      <Head>
        <title>Liberal</title>
        <meta
          name="description"
          content="Generated by create next app"
          charSet="utf-8"
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Page>
          <NavigationBar
            username={userCredentials?.username}
            onLogin={login}
            onLogout={logout}
            isLoggingIn={isLoggingIn}
            primaryButton={
              <Button component="a" href="/new" rightIcon={<File />}>
                New Article
              </Button>
            }
          />
          <Box
            sx={() => ({
              padding: "10px 30px 30px 30px",
            })}
          >
            <Text
              sx={() => ({
                color: "white",
                fontSize: "30px",
              })}
            >
              {username}
            </Text>
          </Box>
        </Page>
      </main>
      <Footer />
    </div>
  );
};

export default Author;
