import axios from "axios";
import { useEffect, useState } from "react";
import type { NextPage } from "next";
import Head from "next/head";
import { useRouter } from "next/router";
import { Box, Button, Text, Pagination } from "@mantine/core";
import { useLogin } from "@soul-project/react-soul-utils";
import { File } from "tabler-icons-react";

import NavigationBar from "src/components/NavigationBar";
import Footer from "src/components/Footer";
import Page from "src/components/Page";
import { useQuery } from "react-query";

const Author: NextPage = () => {
  const router = useRouter();
  const { userId } = router.query;

  const { userCredentials, login, logout, isLoggingIn } = useLogin({
    platformId: 2,
    callback: "http://localhost:3000",
  });
  const [page, setPage] = useState(1);

  const { data } = useQuery(
    [`/api/authors/posts`, userId],
    async () => {
      const { data } = await axios.get<{ posts: Post[]; totalCount: number }>(
        `/api/authors/${userId}/posts`,
        { params: { page: 1 } }
      );

      return data;
    },
    { enabled: !!userId }
  );

  console.log(data);

  return (
    <div>
      <Head>
        <title>Liberal</title>
        <meta
          name="description"
          content="Generated by create next app"
          charSet="utf-8"
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Page>
          <NavigationBar
            username={userCredentials?.username}
            onLogin={login}
            onLogout={logout}
            isLoggingIn={isLoggingIn}
            primaryButton={
              <Button component="a" href="/new" rightIcon={<File />}>
                New Article
              </Button>
            }
          />
          <Box
            sx={() => ({
              padding: "10px 30px 30px 30px",
            })}
          >
            <Text
              sx={() => ({
                color: "white",
                fontSize: "30px",
              })}
            >
              {userCredentials?.username}
            </Text>
            {/* TODO: Display posts with paginator */}
            <Pagination total={10} />
          </Box>
        </Page>
      </main>
      <Footer />
    </div>
  );
};

export default Author;

type Post = {
  cid: string;
  title: string;
};
