import type { NextPage } from "next";
import Head from "next/head";
import { Button } from "@mantine/core";
import { File } from "tabler-icons-react";
import { useLogin } from "@soul-project/react-soul-utils";

import NavigationBar from "../components/NavigationBar";
import Footer from "../components/Footer";
import Page from "../components/Page";

const Home: NextPage = () => {
  const { userCredentials, login, logout, isLoggingIn } = useLogin({
    platformId: 2,
    callback: "http://localhost:3000",
  });

  return (
    <div>
      <Head>
        <title>Liberal</title>
        <meta
          name="description"
          content="Generated by create next app"
          charSet="utf-8"
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Page>
          <NavigationBar
            username={userCredentials?.username}
            onLogin={login}
            onLogout={logout}
            isLoggingIn={isLoggingIn}
            primaryButton={
              <Button component="a" href="/new" rightIcon={<File />}>
                New Article
              </Button>
            }
          />
        </Page>
      </main>
      <Footer />
    </div>
  );
};

export default Home;
