import { useMemo, useState } from "react";
import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import { createEditor, Descendant } from "slate";
import { Editable, ReactEditor, Slate, withReact } from "slate-react";
import { withHistory } from "slate-history";
import { css } from "@emotion/react";

import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  const editor = useMemo(
    () => withHistory(withReact(createEditor() as ReactEditor)),
    []
  );
  const [value, setValue] = useState<Descendant[]>([
    {
      children: [{ text: "" }],
    },
  ]);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta
          name="description"
          content="Generated by create next app"
          charSet="utf-8"
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main
        css={css`
          height: 100vh;
          padding: 50px;
        `}
      >
        <Slate
          editor={editor}
          value={value}
          onChange={(newValue) => setValue(newValue)}
        >
          <Editable
            placeholder="Write something..."
            css={css`
              width: 100%;
              height: 100%;
            `}
          />
        </Slate>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
};

export default Home;
